export const CIRCUIT_PRESETS = {
  blink: {
    id: "blink",
    name: "Blink LED",
    description: "Classic Arduino Uno blink on digital pin 13 with series resistor.",
    workspace: [
      {
        id: "led-1",
        type: "LED_RED",
        pin: 13,
        pins: { main: 13 },
        x: 220,
        y: 260,
      },
      {
        id: "res-1",
        type: "RESISTOR",
        pin: 13,
        pins: { main: 13 },
        resistance: 330,
        x: 140,
        y: 260,
      },
      {
        id: "gnd-1",
        type: "GROUND_NODE",
        pin: 8,
        pins: { main: 8 },
        x: 80,
        y: 360,
      },
      {
        id: "vcc-1",
        type: "VCC_NODE",
        pin: 19,
        pins: { main: 19 },
        x: 80,
        y: 200,
      },
    ],
    outputs: {
      13: 1,
    },
  },
  button_led: {
    id: "button_led",
    name: "Interactive Button + LED",
    description: "Pressing the button on pin 2 lights up the LED on pin 13.",
    workspace: [
      {
        id: "btn-1",
        type: "BUTTON",
        pin: 2,
        pins: { main: 2 },
        x: 100,
        y: 200,
      },
      {
        id: "led-1",
        type: "LED_RED",
        pin: 13,
        pins: { main: 13 },
        x: 220,
        y: 260,
      },
      {
        id: "res-1",
        type: "RESISTOR",
        pin: 13,
        pins: { main: 13 },
        resistance: 330,
        x: 140,
        y: 260,
      },
      {
        id: "gnd-1",
        type: "GROUND_NODE",
        pin: 8,
        pins: { main: 8 },
        x: 80,
        y: 360,
      },
    ],
    outputs: {
      13: 0,
    },
    inputs: {
      2: 0,
    },
  },
  servo_sweep: {
    id: "servo_sweep",
    name: "Servo Sweep",
    description: "A standard hobby servo connected to PWM capable pin 9, sweeping back and forth.",
    workspace: [
      {
        id: "srv-1",
        type: "SERVO",
        pin: 9,
        pins: { main: 9 },
        x: 200,
        y: 150,
      },
      {
        id: "vcc-1",
        type: "VCC_NODE",
        pin: 19,
        pins: { main: 19 },
        x: 150,
        y: 100,
      },
      {
        id: "gnd-1",
        type: "GROUND_NODE",
        pin: 8,
        pins: { main: 8 },
        x: 150,
        y: 200,
      },
    ],
    outputs: {
      9: 0.5,
    },
  },
  timer_555_blink: {
    id: "timer_555_blink",
    name: "555 Timer LED Blinker",
    description: "A classic NE555 astable oscillator driving an LED with timing capacitors.",
    workspace: [
      {
        id: "ic-555",
        type: "TIMER_555",
        pin: 3,
        pins: { main: 3 },
        x: 180,
        y: 180,
      },
      {
        id: "led-timer",
        type: "LED_RED",
        pin: 3,
        pins: { main: 3 },
        x: 300,
        y: 180,
      },
      {
        id: "res-timing",
        type: "RESISTOR",
        pin: 7,
        pins: { main: 7 },
        resistance: 10000,
        x: 130,
        y: 120,
      },
      {
        id: "cap-timing",
        type: "CAPACITOR",
        pin: 6,
        pins: { main: 6 },
        x: 130,
        y: 260,
        metadata: { capacitance: 10, unit: "µF" },
      },
      {
        id: "res-discharge",
        type: "RESISTOR",
        pin: 7,
        pins: { main: 7 },
        resistance: 47000,
        x: 60,
        y: 180,
      },
      {
        id: "vcc-timer",
        type: "VCC_NODE",
        pin: 19,
        pins: { main: 19 },
        x: 60,
        y: 80,
      },
      {
        id: "gnd-timer",
        type: "GROUND_NODE",
        pin: 8,
        pins: { main: 8 },
        x: 60,
        y: 350,
      },
    ],
    outputs: {
      3: 1,
    },
  },
  npn_switch: {
    id: "npn_switch",
    name: "NPN Transistor Switch",
    description: "An NPN BJT used as a digital switch: MCU pin 9 drives the base, collector powers the LED.",
    workspace: [
      {
        id: "q1",
        type: "NPN_TRANSISTOR",
        pin: 9,
        pins: { main: 9 },
        x: 180,
        y: 200,
      },
      {
        id: "led-q",
        type: "LED_GREEN",
        pin: null,
        pins: { main: null },
        x: 260,
        y: 140,
      },
      {
        id: "res-base",
        type: "RESISTOR",
        pin: 9,
        pins: { main: 9 },
        resistance: 1000,
        x: 100,
        y: 200,
      },
      {
        id: "res-collector",
        type: "RESISTOR",
        pin: null,
        pins: { main: null },
        resistance: 330,
        x: 260,
        y: 200,
      },
      {
        id: "vcc-q",
        type: "VCC_NODE",
        pin: 19,
        pins: { main: 19 },
        x: 60,
        y: 100,
      },
      {
        id: "gnd-q",
        type: "GROUND_NODE",
        pin: 8,
        pins: { main: 8 },
        x: 180,
        y: 340,
      },
    ],
    outputs: {
      9: 0,
    },
  },
  buzzer_alarm: {
    id: "buzzer_alarm",
    name: "Buzzer Alarm",
    description: "A piezo buzzer connected to pin 11 with a button trigger on pin 4.",
    workspace: [
      {
        id: "buzz-1",
        type: "BUZZER",
        pin: 11,
        pins: { main: 11 },
        x: 220,
        y: 180,
      },
      {
        id: "btn-alarm",
        type: "BUTTON",
        pin: 4,
        pins: { main: 4 },
        x: 100,
        y: 180,
      },
      {
        id: "res-buzz",
        type: "RESISTOR",
        pin: 11,
        pins: { main: 11 },
        resistance: 100,
        x: 160,
        y: 180,
      },
      {
        id: "gnd-buzz",
        type: "GROUND_NODE",
        pin: 8,
        pins: { main: 8 },
        x: 80,
        y: 320,
      },
    ],
    outputs: {
      11: 0,
    },
    inputs: {
      4: 0,
    },
  },
};
