const thumbFromSlug = (slug) => (slug ? `https://thumbs.wokwi.com/docs/parts/${slug}.html/thumbnail.png` : null);

const REFERENCE_PART_METADATA = {
  LCD1602: { wokwiTag: "wokwi-lcd1602", docSlug: "wokwi-lcd1602" },
  LCD2004: { wokwiTag: "wokwi-lcd2004", docSlug: "wokwi-lcd2004" },
  OLED_SSD1306: { wokwiTag: "wokwi-ssd1306", docSlug: "wokwi-ssd1306" },
  ILI9341_TFT: { wokwiTag: "wokwi-ili9341", docSlug: "wokwi-ili9341" },
  SEVEN_SEG: { wokwiTag: "wokwi-7segment", docSlug: "wokwi-7segment" },
  LED_BAR_GRAPH: { wokwiTag: "wokwi-led-bar-graph", docSlug: "wokwi-led-bar-graph" },
  NEOPIXEL_MATRIX: { wokwiTag: "wokwi-neopixel-matrix", docSlug: "wokwi-led-matrix" },
  NEOPIXEL_RING: { wokwiTag: "wokwi-led-ring", docSlug: "wokwi-led-ring" },
  NEOPIXEL_PIXEL: { wokwiTag: "wokwi-neopixel", docSlug: "wokwi-neopixel" },
  DHT22: { wokwiTag: "wokwi-dht22", docSlug: "wokwi-dht22" },
  NTC_SENSOR: { wokwiTag: "wokwi-ntc-temperature-sensor", docSlug: "wokwi-ntc-temperature-sensor" },
  PHOTORESISTOR: { wokwiTag: "wokwi-photoresistor-sensor", docSlug: "wokwi-photoresistor-sensor" },
  PIR_SENSOR: { wokwiTag: "wokwi-pir-motion-sensor", docSlug: "wokwi-pir-motion-sensor" },
  MPU6050: { wokwiTag: "wokwi-mpu6050", docSlug: "wokwi-mpu6050" },
  HC_SR04: { wokwiTag: "wokwi-hc-sr04", docSlug: "wokwi-hc-sr04" },
  FLAME_SENSOR: { wokwiTag: "wokwi-flame-sensor" },
  GAS_SENSOR: { wokwiTag: "wokwi-gas-sensor", docSlug: "wokwi-gas-sensor" },
  HEARTBEAT_SENSOR: { wokwiTag: "wokwi-heart-beat-sensor" },
  SOUND_SENSOR: { wokwiTag: "wokwi-big-sound-sensor" },
  HX711_LOAD_CELL: { wokwiTag: "wokwi-hx711", docSlug: "wokwi-hx711" },
  HX711_MODULE: { wokwiTag: "wokwi-hx711", docSlug: "wokwi-hx711" },
  BUTTON: { wokwiTag: "wokwi-pushbutton", docSlug: "wokwi-pushbutton" },
  MEMBRANE_KEYPAD: { wokwiTag: "wokwi-membrane-keypad", docSlug: "wokwi-membrane-keypad" },
  ROTARY_ENCODER: { wokwiTag: "wokwi-ky-040", docSlug: "wokwi-ky-040" },
  ANALOG_JOYSTICK: { wokwiTag: "wokwi-analog-joystick", docSlug: "wokwi-analog-joystick" },
  DIP_SWITCH_8: { wokwiTag: "wokwi-dip-switch-8", docSlug: "wokwi-dip-switch-8" },
  ROTARY_DIALER: { wokwiTag: "wokwi-rotary-dialer" },
  LED_RED: { wokwiTag: "wokwi-led", docSlug: "wokwi-led" },
  LED_GREEN: { wokwiTag: "wokwi-led", docSlug: "wokwi-led" },
  LED_YELLOW: { wokwiTag: "wokwi-led", docSlug: "wokwi-led" },
  RGB_LED: { wokwiTag: "wokwi-rgb-led", docSlug: "wokwi-rgb-led" },
  SERVO: { wokwiTag: "wokwi-servo", docSlug: "wokwi-servo" },
  STEPPER_MOTOR: { wokwiTag: "wokwi-stepper-motor", docSlug: "wokwi-stepper-motor" },
  BUZZER: { wokwiTag: "wokwi-buzzer", docSlug: "wokwi-buzzer" },
  DIAL: { wokwiTag: "wokwi-potentiometer", docSlug: "wokwi-potentiometer" },
  SLIDE_POT: { wokwiTag: "wokwi-slide-potentiometer", docSlug: "wokwi-slide-potentiometer" },
  SLIDE_SWITCH: { wokwiTag: "wokwi-slide-switch", docSlug: "wokwi-slide-switch" },
  IR_RECEIVER: { wokwiTag: "wokwi-ir-receiver", docSlug: "wokwi-ir-receiver" },
  IR_REMOTE: { wokwiTag: "wokwi-ir-remote", docSlug: "wokwi-ir-remote" },
  DS1307_RTC: { wokwiTag: "wokwi-ds1307", docSlug: "wokwi-ds1307" },
  MICROSD_MODULE: { wokwiTag: "wokwi-microsd-card", docSlug: "wokwi-microsd-card" },
  RESISTOR: { wokwiTag: "wokwi-resistor", docSlug: "wokwi-resistor" },
  SHIFT_REGISTER: { docSlug: "wokwi-74hc595" },
  LOGIC_ANALYZER_TOOL: { docSlug: "wokwi-logic-analyzer" },
  RELAY_MODULE: { wokwiTag: "wokwi-relay-module", docSlug: "wokwi-relay-module" },
  KEYPAD_MATRIX: { wokwiTag: "wokwi-membrane-keypad", docSlug: "wokwi-membrane-keypad" },
  LED_MATRIX: { wokwiTag: "wokwi-led-matrix", docSlug: "wokwi-led-matrix" },
  ANALOG_TV: { docSlug: "wokwi-tv" },
};

export const COMPONENT_CATEGORIES = [
  {
    id: "displays",
    title: "Displays",
    description: "Character, graphic, and specialty displays",
    components: [
      {
        id: "lcd1602",
        label: "LCD1602 (16x2 LCD)",
        workspaceType: "LCD1602",
        status: "visual",
        icon: "LCD",
        description: "HD44780-compatible 16x2 character module placeholder.",
        terminals: ["VSS", "VDD", "V0", "RS", "RW", "E", "D4", "D5", "D6", "D7", "LED+", "LED-"],
      },
      {
        id: "lcd2004",
        label: "LCD2004 (20x4 LCD)",
        workspaceType: "LCD2004",
        status: "visual",
        icon: "LCD",
        description: "Extended 4-line HD44780 LCD placeholder.",
        terminals: ["VSS", "VDD", "V0", "RS", "RW", "E", "D4", "D5", "D6", "D7", "BACK+", "BACK-"],
      },
      {
        id: "oled_ssd1306",
        label: "OLED Display (SSD1306)",
        workspaceType: "OLED_SSD1306",
        status: "visual",
        icon: "OLED",
        description: "128x64 monochrome OLED (I2C/SPI) placeholder.",
        terminals: ["VCC", "GND", "SCL", "SDA"],
      },
      {
        id: "ili9341",
        label: "ILI9341 TFT Display",
        workspaceType: "ILI9341_TFT",
        status: "visual",
        icon: "TFT",
        description: "2.4\" SPI TFT placeholder.",
        terminals: ["VCC", "GND", "CS", "RESET", "DC", "MOSI", "SCK", "LED"],
      },
      {
        id: "seven_segment",
        label: "7-Segment Display",
        workspaceType: "SEVEN_SEG",
        status: "simulated",
        icon: "7SEG",
        description: "Single common-cathode 7-seg visualized per segment.",
        terminals: ["a", "b", "c", "d", "e", "f", "g"],
      },
      {
        id: "led_bar_graph",
        label: "LED Bar Graph",
        workspaceType: "LED_BAR_GRAPH",
        status: "visual",
        icon: "BAR",
        description: "10-segment LED bar placeholder.",
        terminals: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
      },
      {
        id: "neopixel_matrix",
        label: "NeoPixel Matrix",
        workspaceType: "NEOPIXEL_MATRIX",
        status: "visual",
        icon: "MTRX",
        description: "Addressable RGB matrix placeholder with DIN pin.",
        terminals: ["5V", "DIN", "GND"],
      },
      {
        id: "neopixel_ring",
        label: "NeoPixel LED strip / ring",
        workspaceType: "NEOPIXEL_RING",
        status: "visual",
        icon: "RING",
        description: "Addressable RGB strip/ring placeholder.",
        terminals: ["5V", "DIN", "GND"],
      },
      {
        id: "epaper",
        label: "E-paper Display (basic)",
        workspaceType: "EPAPER_BASIC",
        status: "visual",
        icon: "EPD",
        description: "Slow-refresh e-ink placeholder with SPI pins.",
        terminals: ["VCC", "GND", "SCK", "MOSI", "CS", "DC", "RST", "BUSY"],
      },
      {
        id: "analog_tv",
        label: "TV / Analog Display",
        workspaceType: "ANALOG_TV",
        status: "visual",
        icon: "TV",
        description: "Composite video output placeholder.",
        terminals: ["VIDEO", "GND"],
      },
    ],
  },
  {
    id: "sensors",
    title: "Sensors",
    description: "Environmental, motion, and specialty sensors",
    components: [
      {
        id: "dht22",
        label: "DHT22 Temperature & Humidity",
        workspaceType: "DHT22",
        status: "visual",
        icon: "TEMP",
        description: "Digital humidity/temperature combo sensor placeholder.",
        terminals: ["VCC", "DATA", "GND"],
      },
      {
        id: "ntc_temp",
        label: "NTC Temperature Sensor",
        workspaceType: "NTC_SENSOR",
        status: "visual",
        icon: "NTC",
        description: "Two-wire thermistor placeholder.",
        terminals: ["T1", "T2"],
      },
      {
        id: "ldr",
        label: "Photoresistor (LDR)",
        workspaceType: "PHOTORESISTOR",
        status: "visual",
        icon: "LDR",
        description: "Light-dependent resistor placeholder.",
        terminals: ["L1", "L2"],
      },
      {
        id: "pir",
        label: "PIR Motion Sensor",
        workspaceType: "PIR_SENSOR",
        status: "visual",
        icon: "PIR",
        description: "Passive IR motion module placeholder.",
        terminals: ["VCC", "OUT", "GND"],
      },
      {
        id: "mpu6050",
        label: "MPU6050 IMU",
        workspaceType: "MPU6050",
        status: "visual",
        icon: "IMU",
        description: "I2C accelerometer + gyroscope placeholder.",
        terminals: ["VCC", "GND", "SCL", "SDA"],
      },
      {
        id: "hc_sr04",
        label: "HC-SR04 Ultrasonic",
        workspaceType: "HC_SR04",
        status: "visual",
        icon: "US",
        description: "Trig/Echo ultrasonic distance sensor placeholder.",
        terminals: ["VCC", "TRIG", "ECHO", "GND"],
      },
      {
        id: "flame",
        label: "Flame Sensor",
        workspaceType: "FLAME_SENSOR",
        status: "visual",
        icon: "FLAME",
        description: "Analog flame detector placeholder.",
        terminals: ["AOUT", "DOUT", "VCC", "GND"],
      },
      {
        id: "gas",
        label: "Gas Sensor",
        workspaceType: "GAS_SENSOR",
        status: "visual",
        icon: "GAS",
        description: "MQ-series type gas sensor placeholder.",
        terminals: ["AOUT", "DOUT", "VCC", "GND"],
      },
      {
        id: "heartbeat",
        label: "Heartbeat Sensor",
        workspaceType: "HEARTBEAT_SENSOR",
        status: "visual",
        icon: "HB",
        description: "Pulse/PPG sensor placeholder.",
        terminals: ["VCC", "SIGNAL", "GND"],
      },
      {
        id: "sound",
        label: "Sound Sensor",
        workspaceType: "SOUND_SENSOR",
        status: "visual",
        icon: "MIC",
        description: "Analog microphone module placeholder.",
        terminals: ["AOUT", "DOUT", "VCC", "GND"],
      },
      {
        id: "hx711_load_cell",
        label: "Load Cell (HX711)",
        workspaceType: "HX711_LOAD_CELL",
        status: "visual",
        icon: "HX711",
        description: "Amplifier + strain gauge placeholder.",
        terminals: ["E+", "E-", "A+", "A-", "DT", "SCK", "VCC", "GND"],
      },
    ],
  },
  {
    id: "inputs",
    title: "Input Devices",
    description: "Human-interaction components",
    components: [
      {
        id: "pushbutton",
        label: "Pushbutton",
        workspaceType: "BUTTON",
        status: "simulated",
        icon: "BTN",
        description: "Momentary push button (pull-up friendly).",
      },
      {
        id: "pushbutton_tactile",
        label: "Pushbutton (6mm tactile)",
        workspaceType: "BUTTON",
        status: "simulated",
        icon: "BTN",
        description: "Shares push button model (tactile footprint).",
      },
      {
        id: "membrane_keypad",
        label: "Membrane Keypad",
        workspaceType: "MEMBRANE_KEYPAD",
        status: "visual",
        icon: "KEYP",
        description: "4x4 keypad placeholder.",
        terminals: ["R1", "R2", "R3", "R4", "C1", "C2", "C3", "C4"],
      },
      {
        id: "rotary_encoder",
        label: "Rotary Encoder (KY-040)",
        workspaceType: "ROTARY_ENCODER",
        status: "visual",
        icon: "ENC",
        description: "Incremental encoder placeholder with CLK/DT/SW.",
        terminals: ["CLK", "DT", "SW", "VCC", "GND"],
      },
      {
        id: "analog_joystick",
        label: "Analog Joystick",
        workspaceType: "ANALOG_JOYSTICK",
        status: "visual",
        icon: "JOY",
        description: "Dual-axis joystick placeholder.",
        terminals: ["VRX", "VRY", "SW", "VCC", "GND"],
      },
      {
        id: "dip_switch",
        label: "DIP Switch (8)",
        workspaceType: "DIP_SWITCH_8",
        status: "visual",
        icon: "DIP",
        description: "Eight-position DIP switch placeholder.",
        terminals: ["1", "2", "3", "4", "5", "6", "7", "8", "COM"],
      },
      {
        id: "rotary_dialer",
        label: "Rotary Dialer",
        workspaceType: "ROTARY_DIALER",
        status: "visual",
        icon: "DIAL",
        description: "Pulse dial input placeholder.",
        terminals: ["LINE", "GND"],
      },
    ],
  },
  {
    id: "outputs",
    title: "Output Devices / Actuators",
    description: "LEDs, motors, and audio",
    components: [
      {
        id: "led_red",
        label: "LED (Red)",
        workspaceType: "LED_RED",
        status: "simulated",
        icon: "LED",
        description: "Discrete red LED with resistor helper.",
      },
      {
        id: "led_green",
        label: "LED (Green)",
        workspaceType: "LED_GREEN",
        status: "simulated",
        icon: "LED",
        description: "Discrete green LED.",
      },
      {
        id: "led_yellow",
        label: "LED (Yellow)",
        workspaceType: "LED_YELLOW",
        status: "simulated",
        icon: "LED",
        description: "Discrete yellow LED.",
      },
      {
        id: "rgb_led",
        label: "RGB LED",
        workspaceType: "RGB_LED",
        status: "simulated",
        icon: "RGB",
        description: "Three-channel common-anode RGB LED.",
        terminals: ["r", "g", "b"],
      },
      {
        id: "neopixel",
        label: "NeoPixel",
        workspaceType: "NEOPIXEL_PIXEL",
        status: "visual",
        icon: "NEO",
        description: "Single WS2812 pixel placeholder.",
        terminals: ["5V", "DIN", "GND"],
      },
      {
        id: "led_ring",
        label: "LED Ring",
        workspaceType: "NEOPIXEL_RING",
        status: "visual",
        icon: "RING",
        description: "Addressable LED ring placeholder.",
        terminals: ["5V", "DIN", "GND"],
      },
      {
        id: "servo_motor",
        label: "Servo Motor",
        workspaceType: "SERVO",
        status: "simulated",
        icon: "SRV",
        description: "PWM hobby servo visualized by angle.",
      },
      {
        id: "stepper_motor",
        label: "Stepper Motor (Biaxial)",
        workspaceType: "STEPPER_MOTOR",
        status: "visual",
        icon: "STEP",
        description: "Four-phase stepper placeholder.",
        terminals: ["A+", "A-", "B+", "B-"],
      },
      {
        id: "buzzer",
        label: "Buzzer",
        workspaceType: "BUZZER",
        status: "simulated",
        icon: "BUZZ",
        description: "Piezo buzzer with vibration feedback when active.",
        terminals: ["SIG", "GND"],
      },
    ],
  },
  {
    id: "analog",
    title: "Analog Components",
    description: "Variable resistive elements",
    components: [
      {
        id: "potentiometer",
        label: "Potentiometer",
        workspaceType: "DIAL",
        status: "simulated",
        icon: "POT",
        description: "Analog dial feeding MCU ADC.",
      },
      {
        id: "slide_pot",
        label: "Slide Potentiometer",
        workspaceType: "SLIDE_POT",
        status: "visual",
        icon: "SLIDE",
        description: "Linear slider pot placeholder.",
        terminals: ["VCC", "WIPER", "GND"],
      },
      {
        id: "photoresistor_analog",
        label: "Photoresistor (LDR)",
        workspaceType: "PHOTORESISTOR",
        status: "visual",
        icon: "LDR",
        description: "Shared with sensor catalog entry.",
      },
      {
        id: "ntc_thermistor",
        label: "NTC Thermistor",
        workspaceType: "NTC_SENSOR",
        status: "visual",
        icon: "NTC",
        description: "Shared with environmental sensors.",
      },
    ],
  },
  {
    id: "switches",
    title: "Switches",
    description: "Discrete switching elements",
    components: [
      {
        id: "push_button_switch",
        label: "Push Button",
        workspaceType: "BUTTON",
        status: "simulated",
        icon: "BTN",
        description: "Momentary push button.",
      },
      {
        id: "slide_switch",
        label: "Slide Switch",
        workspaceType: "SLIDE_SWITCH",
        status: "visual",
        icon: "SW",
        description: "SPDT slide switch placeholder.",
        terminals: ["1", "2", "3"],
      },
      {
        id: "dip_switch_switches",
        label: "DIP Switch",
        workspaceType: "DIP_SWITCH_8",
        status: "visual",
        icon: "DIP",
        description: "8-way DIP switch placeholder.",
      },
    ],
  },
  {
    id: "communication",
    title: "Communication & Modules",
    description: "Interface and storage modules",
    components: [
      {
        id: "ir_receiver",
        label: "IR Receiver",
        workspaceType: "IR_RECEIVER",
        status: "visual",
        icon: "IR",
        description: "TSOP-style IR receiver placeholder.",
        terminals: ["OUT", "VCC", "GND"],
      },
      {
        id: "ir_remote",
        label: "IR Remote",
        workspaceType: "IR_REMOTE",
        status: "visual",
        icon: "REMOTE",
        description: "Remote control placeholder emitting codes.",
      },
      {
        id: "ds1307",
        label: "DS1307 RTC Module",
        workspaceType: "DS1307_RTC",
        status: "visual",
        icon: "RTC",
        description: "I2C real-time clock placeholder.",
        terminals: ["VCC", "GND", "SCL", "SDA"],
      },
      {
        id: "microsd",
        label: "microSD Card Module",
        workspaceType: "MICROSD_MODULE",
        status: "visual",
        icon: "SD",
        description: "SPI SD card breakout placeholder.",
        terminals: ["VCC", "GND", "MISO", "MOSI", "SCK", "CS"],
      },
      {
        id: "hx711_module",
        label: "HX711 Amplifier",
        workspaceType: "HX711_MODULE",
        status: "visual",
        icon: "HX711",
        description: "Shared with load cell entry.",
      },
    ],
  },
  {
    id: "passive",
    title: "Passive Components",
    description: "Non-active basics",
    components: [
      {
        id: "resistor",
        label: "Resistor",
        workspaceType: "RESISTOR",
        status: "simulated",
        icon: "RES",
        description: "Adjustable resistance used for limiting current.",
      },
      {
        id: "breadboard",
        label: "Breadboard",
        workspaceType: "BREADBOARD",
        status: "visual",
        icon: "BRD",
        description: "Placeholder for breadboard real estate.",
      },
      {
        id: "wire_node",
        label: "Wires / Nodes",
        workspaceType: "WIRE_NODE",
        status: "simulated",
        icon: "WIRE",
        description: "Routing tie points for wiring system.",
      },
      {
        id: "capacitor",
        label: "Capacitor",
        workspaceType: "CAPACITOR",
        status: "simulated",
        icon: "CAP",
        description: "Ceramic disc capacitor for timing and filtering.",
        terminals: ["T1", "T2"],
      },
      {
        id: "npn_transistor",
        label: "NPN Transistor (BJT)",
        workspaceType: "NPN_TRANSISTOR",
        status: "simulated",
        icon: "NPN",
        description: "NPN bipolar junction transistor for switching and amplification.",
        terminals: ["E", "B", "C"],
      },
      {
        id: "pnp_transistor",
        label: "PNP Transistor (BJT)",
        workspaceType: "PNP_TRANSISTOR",
        status: "simulated",
        icon: "PNP",
        description: "PNP bipolar junction transistor for high-side switching.",
        terminals: ["E", "B", "C"],
      },
      {
        id: "timer_555",
        label: "555 Timer IC",
        workspaceType: "TIMER_555",
        status: "simulated",
        icon: "555",
        description: "NE555 timer IC for astable/monostable oscillator circuits.",
        terminals: ["GND", "TRIG", "OUT", "RESET", "CTRL", "THRES", "DISCH", "VCC"],
      },
    ],
  },
  {
    id: "logic",
    title: "Logic / IC Components",
    description: "Digital helper ICs and tools",
    components: [
      {
        id: "shift_register",
        label: "Shift Register",
        workspaceType: "SHIFT_REGISTER",
        status: "visual",
        icon: "SHIFT",
        description: "8-bit serial-in parallel-out placeholder.",
        terminals: ["VCC", "GND", "SER", "SRCLK", "RCLK", "OE", "MR", "Q0", "Q1", "Q2", "Q3", "Q4", "Q5", "Q6", "Q7"],
      },
      {
        id: "logic_analyzer",
        label: "Logic Analyzer",
        workspaceType: "LOGIC_ANALYZER_TOOL",
        status: "tool",
        icon: "LOGIC",
        description: "Virtual logic analyzer already active in sidebar.",
      },
      {
        id: "digital_chips",
        label: "Digital Chips (Custom)",
        workspaceType: "CUSTOM_DIGITAL_IC",
        status: "visual",
        icon: "ASIC",
        description: "Placeholder for custom digital ICs via API.",
      },
      {
        id: "wasm_ic",
        label: "Custom IC (WebAssembly)",
        workspaceType: "WASM_IC",
        status: "visual",
        icon: "WASM",
        description: "Future WebAssembly-simulated IC placeholder.",
      },
    ],
  },
  {
    id: "misc",
    title: "Miscellaneous Components",
    description: "Relays, keypads, and lab tools",
    components: [
      {
        id: "relay_module",
        label: "Relay Module",
        workspaceType: "RELAY_MODULE",
        status: "visual",
        icon: "RELAY",
        description: "Single-channel relay placeholder.",
        terminals: ["IN", "VCC", "GND", "COM", "NO", "NC"],
      },
      {
        id: "keypad_matrix",
        label: "Keypad Matrix",
        workspaceType: "KEYPAD_MATRIX",
        status: "visual",
        icon: "KEYPAD",
        description: "Shared with membrane keypad entry.",
      },
      {
        id: "matrix_led",
        label: "Matrix LEDs",
        workspaceType: "LED_MATRIX",
        status: "visual",
        icon: "MATRIX",
        description: "8x8 LED matrix placeholder.",
        terminals: ["ROW0", "ROW1", "ROW2", "ROW3", "ROW4", "ROW5", "ROW6", "ROW7", "COL0", "COL1", "COL2", "COL3", "COL4", "COL5", "COL6", "COL7"],
      },
      {
        id: "sd_card_modules",
        label: "SD Card Module",
        workspaceType: "MICROSD_MODULE",
        status: "visual",
        icon: "SD",
        description: "Shared with communication category.",
      },
      {
        id: "serial_monitor",
        label: "Serial Monitor / Logic Tools",
        workspaceType: "SERIAL_MONITOR_TOOL",
        status: "tool",
        icon: "SERIAL",
        description: "Built-in serial monitor already operational.",
      },
    ],
  },
  {
    id: "power",
    title: "Power & Probing",
    description: "Power rails and measurement",
    components: [
      {
        id: "vcc_node",
        label: "VCC Node",
        workspaceType: "VCC_NODE",
        status: "simulated",
        icon: "VCC",
        description: "Provides +5V reference for wiring.",
      },
      {
        id: "ground_node",
        label: "Ground Node",
        workspaceType: "GROUND_NODE",
        status: "simulated",
        icon: "GND",
        description: "Provides GND reference for wiring.",
      },
      {
        id: "multimeter",
        label: "Multimeter",
        workspaceType: "MULTIMETER",
        status: "simulated",
        icon: "MMTR",
        description: "Virtual voltmeter/ADC monitor.",
      },
    ],
  },
];

COMPONENT_CATEGORIES.forEach((category) => {
  category.components = category.components.map((component) => {
    const idKey = typeof component.id === "string" ? component.id.toUpperCase() : undefined;
    const lookup = REFERENCE_PART_METADATA[component.workspaceType] || (idKey ? REFERENCE_PART_METADATA[idKey] : undefined);
    const docSlug = component.docSlug || lookup?.docSlug || null;
    return {
      ...component,
      wokwiTag: component.wokwiTag || lookup?.wokwiTag || null,
      docSlug,
      imageUrl: component.imageUrl || thumbFromSlug(docSlug),
    };
  });
});

export const COMPONENT_TYPE_MAP = COMPONENT_CATEGORIES.reduce((acc, category) => {
  category.components.forEach((component) => {
    if (!component.workspaceType) return;
    if (!acc[component.workspaceType]) {
      acc[component.workspaceType] = { ...component, category: category.title };
    }
  });
  return acc;
}, {});

const supportedTypesMap = new Map();
COMPONENT_CATEGORIES.forEach((category) => {
  category.components.forEach((component) => {
    if (component.status === "simulated" && component.workspaceType) {
      if (!supportedTypesMap.has(component.workspaceType)) {
        supportedTypesMap.set(component.workspaceType, { ...component, category: category.title });
      }
    }
  });
});

export const SUPPORTED_COMPONENTS = Array.from(supportedTypesMap.values());
