export const PIN_LAYOUT = [
  { num: 1, label: "PC6" },
  { num: 2, label: "PD0 (D0)", arduino: 0, port: "D" },
  { num: 3, label: "PD1 (D1)", arduino: 1, port: "D" },
  { num: 4, label: "PD2 (D2)", arduino: 2, port: "D" },
  { num: 5, label: "PD3 (D3)", arduino: 3, port: "D" },
  { num: 6, label: "PD4 (D4)", arduino: 4, port: "D" },
  { num: 7, label: "VCC" },
  { num: 8, label: "GND" },
  { num: 9, label: "PB6", port: "B" },
  { num: 10, label: "PB7", port: "B" },
  { num: 11, label: "PD5 (D5)", arduino: 5, port: "D" },
  { num: 12, label: "PD6 (D6)", arduino: 6, port: "D" },
  { num: 13, label: "PD7 (D7)", arduino: 7, port: "D" },
  { num: 14, label: "PB0 (D8)", arduino: 8, port: "B" },
  { num: 15, label: "PB1 (D9)", arduino: 9, port: "B" },
  { num: 16, label: "PB2 (D10)", arduino: 10, port: "B" },
  { num: 17, label: "PB3 (D11)", arduino: 11, port: "B" },
  { num: 18, label: "PB4 (D12)", arduino: 12, port: "B" },
  { num: 19, label: "PB5 (D13)", arduino: 13, port: "B" },
  { num: 20, label: "AVCC" },
  { num: 21, label: "AREF" },
  { num: 22, label: "GND" },
  { num: 23, label: "PC0 (A0)", port: "C" },
  { num: 24, label: "PC1 (A1)", port: "C" },
  { num: 25, label: "PC2 (A2)", port: "C" },
  { num: 26, label: "PC3 (A3)", port: "C" },
  { num: 27, label: "PC4 (A4)", port: "C" },
  { num: 28, label: "PC5 (A5)", port: "C" }
];
